import React from "react";
import styles from '../styles/Home.module.css'
import Head from 'next/head'


const CreateUser = () => {
    return (
        <div className={styles.container}>
        <Head>
          <title>User Management</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className={styles.main}>
         <h1 >
          Create User
         </h1>

  
        </main>
      </div>
    );
};

export default CreateUser;