import React from "react";
import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Navbar from "../components/layout/navbar/navbar";


const DeleteUser = () => {
    return (
        <div>
        <Head>
          <title>User Management</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main>
        <div>
          <h1>
            Delete User
          </h1>
        </div>

  
        </main>
      </div>
    );
};

export default DeleteUser;