import Head from 'next/head'
// import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
// import Link from 'next/link'
import Navbar from '../components/layout/navbar/navbar'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div >
      <Head>
        <title>User Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <div>
          <h1>
            Smart DB User Management
          </h1>
        </div>

      </main>
    </div>
  )
}
